# Generated by Django 4.1.7 on 2023-02-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cve',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40000, null=True)),
                ('status', models.CharField(blank=True, max_length=40000, null=True)),
                ('description', models.CharField(blank=True, max_length=40000, null=True)),
                ('references', models.CharField(blank=True, max_length=40000, null=True)),
                ('phase', models.CharField(blank=True, max_length=40000, null=True)),
                ('votes', models.CharField(blank=True, max_length=40000, null=True)),
                ('comments', models.CharField(blank=True, max_length=40000, null=True)),
            ],
        ),
    ]
