# Generated by Django 4.1.7 on 2023-02-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_cve_cvemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvemodel',
            options={'ordering': ['id'], 'verbose_name_plural': 'Cve'},
        ),
        migrations.AlterModelTable(
            name='cvemodel',
            table='api_cve',
        ),
    ]
